
export interface IGetAllQaCategoryProductResponse {
    statuscode: number;
    message: string;
    data: IQuestionProductData[];
}

export interface IQuestionProductData {
    WebSiteGuid: string | null;
    ProductGuid: string;
    ProductName: string;
    ProductCode: string;
    ProductSKUs: any | null;
    Description: string | null;
    ProductVirtualSampleLink: string | null;
    DisplayOrder: number | null;
    AsiProductCode: string | null;
    LanguageGuid: string | null;
    FurtherDescription: string | null;
    TagAttributes: any | null;
    PageTitle: string | null;
    MetaKeyword: string | null;
    MetaDescription: string | null;
    MinPrice: number | null;
    MinStrikePrice: number | null;
    MinDiscountedPrice: number | null;
    MinDiscountedStrikePrice: number | null;
    DiscountCode: string | null;
    ExpirationDateUtc: string | null;
    IsCallForPrice: boolean | null;
    MinQuantity: number | null;
    MaxQuantity: number | null;
    MaxSampleQuantity: number | null;
    ProductRating: number | null;
    ProductionTimeInDays: number | null;
    CollectionGuids: any | null;
    ProductTemplates: any | null;
    ProductDetails: any | null;
    EventThemes: any | null;
    Industries: any | null;
    ImprintMethods: any | null;
    TopBannerFeatures: any | null;
    Size: any | null;
    Materials: any | null;
    MasterColors: any | null;
    SimilarProduct: any | null;
    ZipCode: string | null;
    StateCode: string | null;
    CountryCode: string | null;
    ExternalURL: string | null;
    UnAssign: any | null;
    Assign: any | null;
    lbUnassignId: any | null;
    lbAssignId: any | null;
    FeaturedIcons: any | null;
    FeaturedIconImageAlt: string | null;
    EventThemesNames: string | null;
    IndustriesNames: string | null;
    ImprintMethodsNames: string | null;
    MaterialsNames: string | null;
    MappedProduct: any | null;
    ProductMediaList: any | null;
    ProductIESFileManagement: any | null;
    MediaGroupMaster: any | null;
    SelectedColorImage: string | null;
    SelectedColorImageAltText: string | null;
    MappedMasterColors: any | null;
    ProductNameForSorting: string | null;
    ProductPDFGuid: string | null;
    IsTemplateUploaded: boolean | null;
    TemplateDeletedName: string | null;
    MinPriceDetail: any | null;
    IsAddedInWishList: boolean;
    CollectionName: string | null;
    CollectionType: string | null;
    ProductCount: number;
    ParentCollectionGuid: string | null;
    CollectionGuid: string | null;
    IsDealOfTheWeekEnabled: boolean | null;
    DealOfTheWeekStartDate: string | null;
    DealOfTheWeekEndDate: string | null;
    ProductPricing: any | null;
    ProductCodeForSorting: string | null;
    ERPProductId: number;
    IsBillableSample: boolean;
    CanonicalLink: string | null;
    MetaRobots: string | null;
    IsExcludedFromSitemap: boolean;
    ProductAliasName: string;
    IsBlank: boolean;
    AreSamplesAvailable: boolean;
    UploadArtwork: boolean;
    CartonGuids: any | null;
    PerLotItems: any | null;
    HideStep1: any | null;
    SupplierItemId: any | null;
    PopularProductCount: number;
    FOBdetails: any | null;
    MapProductGroups: any | null;
    MapGuid: any | null;
    IsAdminUpdated: boolean;
    ReviewCount: number | null;
    IsShowReviewCount: boolean;
    D365ErrorMessage: string | null;
    ERPBusinessCentralProductId: string | null;
    CustomField: string | null;
    CustomField1: string | null;
    ProductID: string | null;
    PriceHighlighterNumber: number | null;
    DecimalPrecision: number | null;
    Score: number;
    EncodedProductName: string;
    ProductNameWithCode: string;
    ASIResponse: any | null;
    SageResponse: any | null;
    SageCanadaProductId: string | null;
    CombinationKeyword: string | null;
    ProductSuppliers: any | null;
    SimilarProductNames: any | null;
    SimilarProductNamesOld: any | null;
    ExternalProductId: string | null;
    KitProduct: any | null;
    InternalProductCode: string | null;
    ProductOld: any | null;
    IsImageUpdated: boolean | null;
    IsProductMirroring: boolean | null;
    DefaultCollection: any | null;
    IncomingInventoryMessage: string | null;
    IncomingExpectedDate: string | null;
    isShowSavePrice: boolean;
    SupplierName: string | null;
    POInventory: any | null;
    PODate: string | null;
    POFlag: boolean | null;
    NoStockFlag: boolean | null;
    DefaultCategory: string | null;
    CustomProductCodeForSort: string | null;
    IsSageError: boolean;
    CustomField2: string | null;
    City: string | null;
    IsProductFreeShipping: boolean | null;
    IsCustomProduct: boolean | null;
    MadeToOrder: boolean;
    IsArtworkUploaded: boolean;
    WarehouseGuids: any | null;
    OMSProductId: number;
    ShowWarningLabel1: boolean;
    ShowWarningLabel2: boolean;
    NotesText3: string | null;
    NotesText3ExpiryDate: string | null;
    PromoStandardField: string | null;
    IsExcludedFromSage: boolean;
    IsExcludedFromASI: boolean;
    ImprintIsTemplateUploaded: boolean | null;
    OldImprintFileName: string | null;
    ImrintPdfFileName: string | null;
    FOBPoints: any | null;
    ArtworkTemplateURL: string | null;
    ProductNetsuiteId: string | null;
    NetsuiteResponse: any | null;
    DCCategory: string | null;
    DCSubCategory: string | null;
    SkuNetsuiteIds: any | null;
    ASIKeywords: string | null;
    SAGEKeywords: string | null;
    DCKeywords: string | null;
    NetsuiteKeywords: string | null;
    FourthMinPrice: number | null;
    FourthMinDiscountedPrice: number | null;
    FourthMinStrikePrice: number | null;
    FourthMinDiscountedStrikePrice: number | null;
    DCResponse: any | null;
    DCResponseError: any | null;
    IsSKUCartonsAvailable: boolean | null;
    aiResponse: boolean;
    IsUnPublished: boolean;
    imagename: string | null;
    SupplierGuid: string | null;
    IsActive: boolean | null;
    IPAddress: string | null;
    CreatedBy: string | null;
    CreatedDateUtc: string | null;
    ModifiedBy: string | null;
    ModifiedDateUtc: string | null;
    IsDeleted: boolean | null;
}
