export interface IPriceCalculation {
    statuscode: number
    message: string
    data: PriceData
}

export interface PriceData {
    totalamount: number
    salestax: number
    discountamount: number
    promocodealert: any
    freightcharge: number
    customergroupdiscount: number
    basketlist: Basketlist[]
}

export interface Basketlist {
    imagealttext: string
    basketdetailsguid: string
    skuguid: string
    imagename: any
    productname: string
    productcode: string
    skuname: string
    productguid: string
    quantity: number
    totalquantity: number
    userguid: string
    sessionguid: string
    price: number
    totalcartamount: number
    totalproductamount: number
    variantsize: string
    variantimagename: string
    currencyguid: string
    currencycode: any
    minquantity: number
    artworkfilename: any
    cartonheight: string
    cartonlength: string
    cartonweight: string
    cartonwidth: string
    unitspercarton: string
    statecode: string
    country: string
    postalcode: string
    freightcharge: any
    freightname: any
    subtotal: any
    imprintmethodguid: string
    imprintmethodname: any
    imprintlocations: Imprintlocation[]
    numberofimprintcolors: number
    numberofimprintlocations: number
    chargeslist: any[]
    conditionname: any
    conditionrule: any
    discountamount: any
    minorderamount: any
    discountpercentage: any
    actualprice: number
    promotionconditionguid: any
    actualtotalamount: number
    isapplyonproductbaseprice: boolean
    isapplyonitemandchargeprice: boolean
    isapplysitewide: boolean
    isalluserselected: boolean
    isallcustomergroupselected: boolean
    maximumdiscountamount: any
    isapplyonbasketprice: boolean
    totalamountafterpromotion: number
    totalamountbeforepromotion: number
    totaldiscountamount: number
    totalproductorderamount: number
    freesetupchargenote: boolean
    promotiontotalnote: any
    promotionproductnote: any
    flag: any
    collectionguids: any
    applydiscounttocollectionguids: any
    applydiscounttoproductguids: any
    productguids: any
    shippingmethodguids: any
    shippingstateguids: any
    freighttypename: any
    shippernumber: any
    pricingguid: string
    previousorderno: any
    artvaultguid: any
    artvaulturl: any
    discountshippingpercentage: any
    issample: boolean
    isbillablesample: boolean
    erpproductid: number
    erpskuid: string
    cartid: string
    questionanswer: any
    shipcarrier: any
    applicablepromotions: any[]
    existingpromotions: any
    promotionalnotes: any[]
    pricetodisplay: number
    actualquantity: number
    discountedshippingtype: any
    isfreesetup: any
    promocodealert: any
    promocodes: any
    isfromcheckout: boolean
    totalamounttodisplay: number
    totalamountdiscount: number
    promotionalnotesfortotal: any[]
    cartcharges: any
    shoppingcartid: any
    shoppingcartitemid: any
    uploadartwork: boolean
    instructions: string
    productaliasname: string
    customfieldtext: string
    unitwt: any
    decimalprecision: any
    editorderguid: any
    fromaddtocart: boolean
    artvaultinstructions: any
    suppliername: string
    groupguid: string
    variantupcharge: string
    vintage: any
    priceperquantity: any
    pricingname: string
    skucode: string
    size: any
    featurediconsdata: any
    pspreorderdetail: any
    isproductfreeshipping: boolean
    iscustomproduct: boolean
    psreorder: boolean
    artworktext: string
    customfield2: string
    isartworkuploaded: boolean
    vertextaxcharge: number
    vsimagelinks: any
    vslink: any
    totalprice: any
    requestquotenumber: any
    requestquoteguid: any
    customfield: any
    skucustomfield: any
    productiontime: string
    pmscharges: number
    variants: any
    customizeproductdetails: any
    artvaultlist: any
    productcustomcharges: any
}

export interface Imprintlocation {
    imprintlocationguid: string
    imprintlocationname: any
    imprintcolors: string[]
    imprintcustomcolors: any
    imprintcolorguid: any
}
