import { gql } from "@apollo/client";

export const useQueryGetCategoryDetailsForEdit = gql`
 query getcategoryDetailsForEdit($collectionGuid: String!) {
  categoryDetailsForEdit(collectionGuid: $collectionGuid) {
    message
    statuscode
    success
    data {
      collectionBannerDim
      collectionBannerImageSize
      collectionImageDim
      menuBannerImageDim
      offerBannerImageDim
      categoryData {
        alias
        asiCategoryName
        bannerImageAlt
        bannerText
        canonicalLink
        categorylistingImageAlt
        categorylistingImageName
        collectionBannerImageName
        collectionGuid
        collectionImageAlt
        collectionImageName
        collectionName
        collectionType
        createdBy
        createdDateUtc
        dcCategoryName
        dcSubCategoriesName
        descriptionText
        displayOrder
        featuredIconURL
        featureIconImageAlt
        furtherDescriptionText
        h1Tag
        iconImageName
        ipAddress
        isActive
        isAllAssignedProducts
        isBottomNode
        isExcludedFromSitemap
        isNewSection
        isProductMirroring
        languageGuid
        menuBannerImageAlt
        menuBannerImageName
        metaDescription
        metaKeywords
        metaRobots
        metaTitle
        mirrorCollectionGuid
        modifiedBy
        modifiedDateUtc
        offerBannerImageAlt
        offerBannerImageName
        parentCollectionGuid
        parentCollectionName
        productCount
        resoAlias
        resoASICategoryName
        resoBannerImageAlt
        resoBannerText
        resoCanonicalLink
        resoCollectionBannerImageName
        resoCollectionGuid
        resoCollectionImageAlt
        resoCollectionImageName
        resoCollectionName
        resoCollectionType
        resoDCCategoryName
        resoDCSubCategoriesName
        resoDescriptionText
        resoFeaturedIconURL
        resoFeatureIconImageAlt
        resoFurtherDescriptionText
        resoH1Tag
        resoIconImageName
        resoIsAllAssignedProducts
        resoIsBottomNode
        resoIsExcludedFromSitemap
        resoIsProductMirroring
        resoMenuBannerImageAlt
        resoMenuBannerImageName
        resoMetaDescription
        resoMetaKeywords
        resoMetaRobots
        resoMetaTitle
        resoMirrorCollectionGuid
        resoOfferBannerImageAlt
        resoOfferBannerImageName
        resoParentCollectionGuid
        resoParentCollectionName
        resoSageCategoryName
        sageCategoryName
        sapCategoryID
        websiteGuid
        bannerListingImages {
          altText
          bannerImageGuid
          bannerName
          displayOrder
          navigateUrl
        }
        resoBannerListingImages {
          altText
          bannerImageGuid
          bannerName
          displayOrder
          navigateUrl
        }
        slideShowImages {
          altText
          displayOrder
          imageName
          isNewWindow
          navigateUrl
          overlayText
          slideShowImageGuid
        }
        resoSlideShowImages {
          altText
          displayOrder
          imageName
          isNewWindow
          navigateUrl
          overlayText
          slideShowImageGuid
        }
        resolstAssignProd {
          aiResponse
          areSamplesAvailable
          asiKeywords
          asiProductCode
          asiResponse
          assign
          canonicalLink
          cartonGuids
          city
          collectionGuid
          collectionName
          collectionType
          combinationKeyword
          countryCode
          createdBy
          createdDateUtc
          customField
          customField1
          customField2
          customProductCodeForSort
          d365ErrorMessage
          dcCategory
          dcKeywords
          dcResponse
          dcSubCategory
          dealOfTheWeekEndDate
          dealOfTheWeekStartDate
          decimalPrecision
          defaultCategory
          defaultCollection
          description
          discountCode
          displayOrder
          encodedProductName
          erpBusinessCentralProductId
          erpProductId
          eventThemes
          eventThemesNames
          expirationDateUtc
          externalProductId
          externalURL
          featuredIconImageAlt
          featuredIcons
          fourthMinDiscountedPrice
          fourthMinDiscountedStrikePrice
          fourthMinPrice
          fourthMinStrikePrice
          furtherDescription
          hideStep1
          imprintIsTemplateUploaded
          imprintMethods
          imprintMethodsNames
          imrintPdfFileName
          incomingExpectedDate
          incomingInventoryMessage
          industries
          industriesNames
          internalProductCode
          ipAddress
          isActive
          isAddedInWishList
          isAdminUpdated
          isArtworkUploaded
          isBillableSample
          isBlank
          isCallForPrice
          isCustomProduct
          isDealOfTheWeekEnabled
          isDeleted
          isExcludedFromASI
          isExcludedFromSage
          isExcludedFromSitemap
          isImageUpdated
          isProductFreeShipping
          isProductMirroring
          isSageError
          isShowReviewCount
          isShowSavePrice
          isSKUCartonsAvailable
          isTemplateUploaded
          isUnPublished
          kitProduct
          languageGuid
          lbAssignId
          lbUnassignId
          madeToOrder
          mapGuid
          mappedMasterColors
          mappedProduct
          materials
          materialsNames
          maxQuantity
          maxSampleQuantity
          metaDescription
          metaKeyword
          metaRobots
          minDiscountedPrice
          minDiscountedStrikePrice
          minPrice
          minQuantity
          minStrikePrice
          modifiedBy
          modifiedDateUtc
          netsuiteKeywords
          netsuiteResponse
          noStockFlag
          notesText3
          notesText3ExpiryDate
          oldImprintFileName
          omsProductId
          pageTitle
          parentCollectionGuid
          perLotItems
          poDate
          poFlag
          poInventory
          popularProductCount
          priceHighlighterNumber
          productAliasName
          productCode
          productCodeForSorting
          productCount
          productGuid
          productID
          productionTimeInDays
          productName
          productNameForSorting
          productNameWithCode
          productNetsuiteId
          productPDFGuid
          productRating
          productSuppliers
          productVirtualSampleLink
          reviewCount
          sageCanadaProductId
          sageKeywords
          sageResponse
          score
          selectedColorImage
          selectedColorImageAltText
          showWarningLabel1
          showWarningLabel2
          similarProduct
          similarProductNames
          similarProductNamesOld
          size
          stateCode
          supplierItemId
          supplierName
          tagAttributes
          templateDeletedName
          topBannerFeatures
          unAssign
          uploadArtwork
          warehouseGuids
          webSiteGuid
          zipCode
          artworkTemplateURL {
            name
            url
          }
        }
        resolstUnAssignProd {
          aiResponse
          areSamplesAvailable
          asiKeywords
          asiProductCode
          asiResponse
          assign
          canonicalLink
          cartonGuids
          city
          collectionGuid
          collectionName
          collectionType
          combinationKeyword
          countryCode
          createdBy
          createdDateUtc
          customField
          customField1
          customField2
          customProductCodeForSort
          d365ErrorMessage
          dcCategory
          dcKeywords
          dcResponse
          dcSubCategory
          dealOfTheWeekEndDate
          dealOfTheWeekStartDate
          decimalPrecision
          defaultCategory
          defaultCollection
          description
          discountCode
          displayOrder
          encodedProductName
          erpBusinessCentralProductId
          erpProductId
          eventThemes
          eventThemesNames
          expirationDateUtc
          externalProductId
          externalURL
          featuredIconImageAlt
          featuredIcons
          fourthMinDiscountedPrice
          fourthMinDiscountedStrikePrice
          fourthMinPrice
          fourthMinStrikePrice
          furtherDescription
          hideStep1
          imprintIsTemplateUploaded
          imprintMethods
          imprintMethodsNames
          imrintPdfFileName
          incomingExpectedDate
          incomingInventoryMessage
          industries
          industriesNames
          internalProductCode
          ipAddress
          isActive
          isAddedInWishList
          isAdminUpdated
          isArtworkUploaded
          isBillableSample
          isBlank
          isCallForPrice
          isCustomProduct
          isDealOfTheWeekEnabled
          isDeleted
          isExcludedFromASI
          isExcludedFromSage
          isExcludedFromSitemap
          isImageUpdated
          isProductFreeShipping
          isProductMirroring
          isSageError
          isShowReviewCount
          isShowSavePrice
          isSKUCartonsAvailable
          isTemplateUploaded
          isUnPublished
          kitProduct
          languageGuid
          lbAssignId
          lbUnassignId
          madeToOrder
          mapGuid
          mappedMasterColors
          mappedProduct
          materials
          materialsNames
          maxQuantity
          maxSampleQuantity
          metaDescription
          metaKeyword
          metaRobots
          minDiscountedPrice
          minDiscountedStrikePrice
          minPrice
          minQuantity
          minStrikePrice
          modifiedBy
          modifiedDateUtc
          netsuiteKeywords
          netsuiteResponse
          noStockFlag
          notesText3
          notesText3ExpiryDate
          oldImprintFileName
          omsProductId
          pageTitle
          parentCollectionGuid
          perLotItems
          poDate
          poFlag
          poInventory
          popularProductCount
          priceHighlighterNumber
          productAliasName
          productCode
          productCodeForSorting
          productCount
          productGuid
          productID
          productionTimeInDays
          productName
          productNameForSorting
          productNameWithCode
          productNetsuiteId
          productPDFGuid
          productRating
          productSuppliers
          productVirtualSampleLink
          reviewCount
          sageCanadaProductId
          sageKeywords
          sageResponse
          score
          selectedColorImage
          selectedColorImageAltText
          showWarningLabel1
          showWarningLabel2
          similarProduct
          similarProductNames
          similarProductNamesOld
          size
          stateCode
          supplierItemId
          supplierName
          tagAttributes
          templateDeletedName
          topBannerFeatures
          unAssign
          uploadArtwork
          warehouseGuids
          webSiteGuid
          zipCode
          artworkTemplateURL {
            name
            url
          }
        }
        lstUnAssignProd {
          aiResponse
          areSamplesAvailable
          asiKeywords
          asiProductCode
          asiResponse
          assign
          canonicalLink
          cartonGuids
          city
          collectionGuid
          collectionName
          collectionType
          combinationKeyword
          countryCode
          createdBy
          createdDateUtc
          customField
          customField1
          customField2
          customProductCodeForSort
          d365ErrorMessage
          dcCategory
          dcKeywords
          dcResponse
          dcSubCategory
          dealOfTheWeekEndDate
          dealOfTheWeekStartDate
          decimalPrecision
          defaultCategory
          defaultCollection
          description
          discountCode
          displayOrder
          encodedProductName
          erpBusinessCentralProductId
          erpProductId
          eventThemes
          eventThemesNames
          expirationDateUtc
          externalProductId
          externalURL
          featuredIconImageAlt
          featuredIcons
          fourthMinDiscountedPrice
          fourthMinDiscountedStrikePrice
          fourthMinPrice
          fourthMinStrikePrice
          furtherDescription
          hideStep1
          imprintIsTemplateUploaded
          imprintMethods
          imprintMethodsNames
          imrintPdfFileName
          incomingExpectedDate
          incomingInventoryMessage
          industries
          industriesNames
          internalProductCode
          ipAddress
          isActive
          isAddedInWishList
          isAdminUpdated
          isArtworkUploaded
          isBillableSample
          isBlank
          isCallForPrice
          isCustomProduct
          isDealOfTheWeekEnabled
          isDeleted
          isExcludedFromASI
          isExcludedFromSage
          isExcludedFromSitemap
          isImageUpdated
          isProductFreeShipping
          isProductMirroring
          isSageError
          isShowReviewCount
          isShowSavePrice
          isSKUCartonsAvailable
          isTemplateUploaded
          isUnPublished
          kitProduct
          languageGuid
          lbAssignId
          lbUnassignId
          madeToOrder
          mapGuid
          mappedMasterColors
          mappedProduct
          materials
          materialsNames
          maxQuantity
          maxSampleQuantity
          metaDescription
          metaKeyword
          metaRobots
          minDiscountedPrice
          minDiscountedStrikePrice
          minPrice
          minQuantity
          minStrikePrice
          modifiedBy
          modifiedDateUtc
          netsuiteKeywords
          netsuiteResponse
          noStockFlag
          notesText3
          notesText3ExpiryDate
          oldImprintFileName
          omsProductId
          pageTitle
          parentCollectionGuid
          perLotItems
          poDate
          poFlag
          poInventory
          popularProductCount
          priceHighlighterNumber
          productAliasName
          productCode
          productCodeForSorting
          productCount
          productGuid
          productID
          productionTimeInDays
          productName
          productNameForSorting
          productNameWithCode
          productNetsuiteId
          productPDFGuid
          productRating
          productSuppliers
          productVirtualSampleLink
          reviewCount
          sageCanadaProductId
          sageKeywords
          sageResponse
          score
          selectedColorImage
          selectedColorImageAltText
          showWarningLabel1
          showWarningLabel2
          similarProduct
          similarProductNames
          similarProductNamesOld
          size
          stateCode
          supplierItemId
          supplierName
          tagAttributes
          templateDeletedName
          topBannerFeatures
          unAssign
          uploadArtwork
          warehouseGuids
          webSiteGuid
          zipCode
          artworkTemplateURL {
            name
            url
          }
        }
        lstAssignProd {
          aiResponse
          areSamplesAvailable
          asiKeywords
          asiProductCode
          asiResponse
          assign
          canonicalLink
          cartonGuids
          city
          collectionGuid
          collectionName
          collectionType
          combinationKeyword
          countryCode
          createdBy
          createdDateUtc
          customField
          customField1
          customField2
          customProductCodeForSort
          d365ErrorMessage
          dcCategory
          dcKeywords
          dcResponse
          dcSubCategory
          dealOfTheWeekEndDate
          dealOfTheWeekStartDate
          decimalPrecision
          defaultCategory
          defaultCollection
          description
          discountCode
          displayOrder
          encodedProductName
          erpBusinessCentralProductId
          erpProductId
          eventThemes
          eventThemesNames
          expirationDateUtc
          externalProductId
          externalURL
          featuredIconImageAlt
          featuredIcons
          fourthMinDiscountedPrice
          fourthMinDiscountedStrikePrice
          fourthMinPrice
          fourthMinStrikePrice
          furtherDescription
          hideStep1
          imprintIsTemplateUploaded
          imprintMethods
          imprintMethodsNames
          imrintPdfFileName
          incomingExpectedDate
          incomingInventoryMessage
          industries
          industriesNames
          internalProductCode
          ipAddress
          isActive
          isAddedInWishList
          isAdminUpdated
          isArtworkUploaded
          isBillableSample
          isBlank
          isCallForPrice
          isCustomProduct
          isDealOfTheWeekEnabled
          isDeleted
          isExcludedFromASI
          isExcludedFromSage
          isExcludedFromSitemap
          isImageUpdated
          isProductFreeShipping
          isProductMirroring
          isSageError
          isShowReviewCount
          isShowSavePrice
          isSKUCartonsAvailable
          isTemplateUploaded
          isUnPublished
          kitProduct
          languageGuid
          lbAssignId
          lbUnassignId
          madeToOrder
          mapGuid
          mappedMasterColors
          mappedProduct
          materials
          materialsNames
          maxQuantity
          maxSampleQuantity
          metaDescription
          metaKeyword
          metaRobots
          minDiscountedPrice
          minDiscountedStrikePrice
          minPrice
          minQuantity
          minStrikePrice
          modifiedBy
          modifiedDateUtc
          netsuiteKeywords
          netsuiteResponse
          noStockFlag
          notesText3
          notesText3ExpiryDate
          oldImprintFileName
          omsProductId
          pageTitle
          parentCollectionGuid
          perLotItems
          poDate
          poFlag
          poInventory
          popularProductCount
          priceHighlighterNumber
          productAliasName
          productCode
          productCodeForSorting
          productCount
          productGuid
          productID
          productionTimeInDays
          productName
          productNameForSorting
          productNameWithCode
          productNetsuiteId
          productPDFGuid
          productRating
          productSuppliers
          productVirtualSampleLink
          reviewCount
          sageCanadaProductId
          sageKeywords
          sageResponse
          score
          selectedColorImage
          selectedColorImageAltText
          showWarningLabel1
          showWarningLabel2
          similarProduct
          similarProductNames
          similarProductNamesOld
          size
          stateCode
          supplierItemId
          supplierName
          tagAttributes
          templateDeletedName
          topBannerFeatures
          unAssign
          uploadArtwork
          warehouseGuids
          webSiteGuid
          zipCode
          artworkTemplateURL {
            name
            url
          }
        }
      }
      listCollectionTypes {
        collectionTypeGuid
        collectionTypeName
        isActive
      }
      listParentCollections {
        disabled
        imagename
        parentcategoryguid
        selected
        text
        value
        categorytype
      }
      listDC {
        disabled
        selected
        text
        value
      }
      listSage {
        disabled
        selected
        text
        value
      }
      listAsi {
        disabled
        selected
        text
        value
      }
      listpageSage {
        disabled
        selected
        text
        value
      }
        listSubDC {
        disabled
        selected
        text
        value
      }
    }
  }
}
`;
