export type CookieDetails = {
    [index: string]: any;
    UserGuid: string;
    EmailAddress: string;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    WebsiteURL: string;
    SessionGuid: string;
    Phone: string;
    CountryGUID: string;
    LastLogin: Date;
    LanguageId: number;
    IsActive: boolean;
    RoleId: number;
    UserType: any;
    WebsiteGuid: string;
    RoleName: string;
    PermissionGuids: any;
    PermissionDetailGuids: any;
    AdminMenu: any;
    IsGuestUser: any;
    RememberMe: boolean;
    RememberExpirationTime: any;
    IsOrderEdit: boolean;
    EditOrder_CustomerGuid: any;
    EditCurrencyGuid: any;
    EditOrderGuid: any;
    IsOTPLogin: boolean;
    PromotionCode: string;
    PromotionAmount: string;
};
