export interface IHeaders {
    ActionType?: string;
    fileName?: string;
    Guid?: string;
    Islast?: boolean;
    Qqfile?: string;
    Qqpartindex?: string;
    Qqtotalfilesize?: string;
    Qqtotalparts?: string;
    DefaultLanguageGuid?: string;
    DefaultCurrencyGuid?: string;
    LanguageGuid?: string;
    WebsiteGuid?: string;
    WebsiteURL?: string;
    SessionGuid?: string;
    Accept?: string;
    Authorization?: string;
    SiteCssVersion?: string;
    "content-type"?: string;
    CookieDetails?: any;
    CurrencyGuid?: string;
    CurrencySymbol?: string;
    WebsiteName?: string;
    WishlistCount?: string | number;
    WishlistName?: string;
    pageno?: number;
    pagesize?: number;
    ReviewCount?: number;
    ProductGuid?: string;
    ProductCount?: number;
    IsCarouselEnable?: boolean;
    IsSeeAll?: boolean;
    isPagination?: boolean;
    Keyword?: string;
    CategoryGuid?: string;
    FileName?: string;
    ImageType?: string;
    ImageSize?: string;
    DownloadFileName?: string;
    ProductName?: string;
    categoryAlias?: string;
    BasketDetailGuid?: string;
    type?: string;
    action?: string;
    orderid?: string;
    CurrentSlidePosition?: string;
    FileData?: any;
    isLast?: any;
    qqtotalparts?: any;
    qqpartindex?: any;
    qqtotalfilesize?: any;
    ax_allow_ext?: any;
    ax_maxfilesize?: any;
    fileName2?: any;
    submitpoguid1?: any;
    qqfile?: any;
    guid?: any;
    actiontype?: string;
    qqchunksize?: any;
    Url?: string;
    UserGuid?: string;
    ProductCode?: string;
    ViewedProductCount?: number;
    AddressGuid?: string;
    IsConsiderForRecomm?: boolean;
    RecommendationType?: string;
    isMediaData?: boolean;
    isFurtherDescription?: boolean;
    isSKUVM?: boolean;
    isEventThemes?: boolean;
    isIndustries?: boolean;
    PageNo?: number;
    PageSize?: number;
}

export type IMicroserviceName = "SaaS_Configuration_Microservice" | "SaaS_GlobalElements_Microservice" | "SaaS_ReviewManagement_Microservice" | "SaaS_Product_Microservice" | "SaaS_HTMLConfigurator_Microservice" | "SaaS_VirtualSample_Microservice" | "SaaS_Users_Microservice" | "SaaS_User_Microservice" | "SaaS_Basket_Microservice" | "SaaS_Order_Microservice" | "SaaS_Analytics_Microservice" | "SaaS_Catalog_Microservice" | "SaaS_Freight_Microservice" | "SaaS_ERPIntegration_Microservice" | "SaaS_ProductImportExport_Microservice" | "SaaS_Product_GlobalElements_Microservice" | "SaaS_ProductListing_Microservice" | "SaaS_ProductAdmin_Microservice" | "SaaS_ProductDetails_Microservice" | "SaaS_ProductListing_Microservice_URL" | "SaaS_ControlPanel_Microservice";

export interface ICallOptions {
    url: string;
    type: "GET" | "POST" | "HEAD" | "PUT" | "DELETE";
    headers?: IHeaders;
    /** Convert the object to a string using JSON.stringify() before passing it to data */
    data?: string;
    isAsync?: boolean;
    contentType?: boolean | string;
    MicroserviceName: IMicroserviceName;
    OnSuccess: (response: any) => void;
    OnError?: (reason: any) => void;
}
